vhm: fix vhm_vm_mngt.h compile fail with CONFIG_PREEMPT_RT_FULL
When both CONFIG_PREEMPT_RT_FULL & CONFIG_ACRN_SHARED_BUFFER are
enabled, compile fail:

/include/linux/rwlock_types.h:24:3: error: conflicting types for ‘rwlock_t’
In file included from ./include/linux/spinlock_types.h:20,
                 from ./include/linux/spinlock.h:82,
                 from ./include/linux/mmzone.h:8,
                 from ./include/linux/gfp.h:6,
                 from drivers/acrn/sbuf.c:58:
./include/linux/rwlock_types_rt.h:14:27: note: previous declaration of ‘rwlock_t’ was here
In file included from ./include/linux/vhm/vhm_vm_mngt.h:64,
                 from ./include/linux/vhm/acrn_vhm_mm.h:62,
                 from drivers/acrn/sbuf.c:63:

There are 'include/linux/rwlock_types_rt.h' & 'include/linux/rwlock_types.h'.
Include rwlock_types_rt.h when CONFIG_PREEMPT_RT_FULL is enabled,
otherwise include  rwlock_types.h.
That is selected in 'linux/spinlock_types.h', so include spinlock_types.h
instead of rwlock_types.h, to avoid compile problem.

Signed-off-by: Tao Yuhong <yuhong.tao@intel.com>